MediaCollection/Controllers/MediaController.cs
using MediaCollection.ServiceLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaCollection.Controllers
{
    public class MediaController : Controller
    {
        private readonly MediaService _mediaService;

        public MediaController(MediaService mediaService)
        {
            _mediaService = mediaService ?? throw new ArgumentNullException(nameof(MediaService));
        }
        // GET: MediaController
        public ActionResult Index(string searchTitle,string mediaGenre)
        {
            if (!String.IsNullOrEmpty(searchTitle))
            { 
                return View(_mediaService.SearchMediaOnTitle(searchTitle)); 
            }
            else
            {
                if (!String.IsNullOrEmpty(mediaGenre))
                {
                     return View(_mediaService.SearchMediaOnGenre(mediaGenre));
                }
                else
                {
                    return View(_mediaService.ListMedia());
                }
            }
        }
    }
}

MediaCollection/Controllers/MovieController.cs
using MediaCollection.ServiceLayer;
using MediaCollection.ServiceLayer.ViewModels;
using MediaCollection.ServiceLayer.ViewModels.MovieViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaCollection.Controllers
{
    public class MovieController : Controller
    {
        private readonly MediaService _mediaService;
        private readonly MovieService _movieService;
        //private readonly AddMovieViewModel _addMovieViewModel;

        public MovieController(MediaService mediaService, MovieService movieService)
        {
            _mediaService = mediaService ?? throw new ArgumentNullException(nameof(MediaService));
            _movieService = movieService ?? throw new ArgumentNullException(nameof(MediaService));
        }

        // GET: MovieController
        public ActionResult Index()
        {
            return View(_mediaService.ListMovies());
        }

        public IActionResult Create()
        {
            return View(_movieService.GetMovieGenres());
        }

        [HttpPost]
        public IActionResult Create([FromForm] AddMovieViewModel addMovieViewModel)
        {
            if (!TryValidateModel(addMovieViewModel))
            {
                return View(addMovieViewModel);
            }

            _movieService.AddMovie(addMovieViewModel);
            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult Details(int id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            var movie = _movieService.GetMovie(id);
            
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        public IActionResult Edit(int id)
        {
            return View(_movieService.GetMovie4Update(id));
        }

        [HttpPost]
        public IActionResult Edit(int id, [FromForm] UpdateMovieViewModel updMovieViewModel)
        {

            if (!TryValidateModel(updMovieViewModel))
            {
                return View(updMovieViewModel);
            }

            _movieService.UpdateMovie(id, updMovieViewModel);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            return View(_movieService.GetMovieToDelete(id));
        }

        [HttpPost]
        public IActionResult ConfirmDelete(int id)
        {
            bool result = _movieService.DeleteMovie(id);
            ViewData["result"] = result.ToString();
            return RedirectToAction(nameof(Index));
        }


        //[HttpGet]

        //public async Task<IActionResult> Create()
        //{
        //    AddMovieViewModel vm = new AddMovieViewModel();
        //    vm.ReleaseDate = DateTime.Now;
        //    return View(vm);
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([FromForm] AddMovieViewModel addMovieViewModel)
        //{
        //    _movieservice.AddMovie(addMovieViewModel);
        //    return RedirectToAction(nameof(Index));
        //}

    }
}




// TO DELETE //
///////////////
// GET: MediaController/Details/5
//public ActionResult Details(int id)
//{
//    return View();
//}

//// GET: MediaController/Create
//public ActionResult Create()
//{
//    return View();
//}

//// POST: MediaController/Create
//[HttpPost]
//[ValidateAntiForgeryToken]
//public ActionResult Create(IFormCollection collection)
//{
//    try
//    {
//        return RedirectToAction(nameof(Index));
//    }
//    catch
//    {
//        return View();
//    }
//}

//// GET: MediaController/Edit/5
//public ActionResult Edit(int id)
//{
//    return View();
//}

//// POST: MediaController/Edit/5
//[HttpPost]
//[ValidateAntiForgeryToken]
//public ActionResult Edit(int id, IFormCollection collection)
//{
//    try
//    {
//        return RedirectToAction(nameof(Index));
//    }
//    catch
//    {
//        return View();
//    }
//}

//// GET: MediaController/Delete/5
//public ActionResult Delete(int id)
//{
//    return View();
//}

//// POST: MediaController/Delete/5
//[HttpPost]
//[ValidateAntiForgeryToken]
//public ActionResult Delete(int id, IFormCollection collection)
//{
//    try
//    {
//        return RedirectToAction(nameof(Index));
//    }
//    catch
//    {
//        return View();
//    }
//}

MediaCollection/Controllers/MusicController.cs
using MediaCollection.ServiceLayer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaCollection.Controllers
{
    public class MusicController : Controller
    {
        private readonly MediaService _mediaService;
        //private readonly MusicService _movieService;
        //private readonly AddMovieViewModel _addMovieViewModel;

        public MusicController(MediaService mediaService, MovieService movieService)
        {
            _mediaService = mediaService ?? throw new ArgumentNullException(nameof(MediaService));
            //_musicService = movieService ?? throw new ArgumentNullException(nameof(MusicService));
        }

        // GET: MovieController
        public ActionResult Index()
        {
            return View(_mediaService.ListMusic());
        }
    }
}

MediaCollection/Controllers/PodcastController.cs
using MediaCollection.ServiceLayer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaCollection.Controllers
{
    public class PodcastController : Controller
    {
        private readonly MediaService _mediaService;
        //private readonly MovieService _movieService;
        //private readonly AddMovieViewModel _addMovieViewModel;

        public PodcastController(MediaService mediaService, MovieService movieService)
        {
            _mediaService = mediaService ?? throw new ArgumentNullException(nameof(MediaService));
        //    _movieService = movieService ?? throw new ArgumentNullException(nameof(MediaService));
        }

        // GET: PodcastController
        public ActionResult Index()
        {
            return View(_mediaService.ListPodcasts());
        }
    }
}

MediaCollection/Controllers/SerieController.cs
using MediaCollection.ServiceLayer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaCollection.Controllers
{
    public class SerieController : Controller
    {
        private readonly MediaService _mediaService;

        public SerieController(MediaService mediaService)
        {
            _mediaService = mediaService ?? throw new ArgumentNullException(nameof(MediaService));
        }
        // GET: MovieController
        public ActionResult Index()
        {
            return View(_mediaService.ListSeries());
        }
    }
}

MediaCollection/Views/Media/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering;
@model MediaCollection.ServiceLayer.ViewModels.ListMediaGenreViewModel

@{
    ViewData["Title"] = "Media List";
}

@*<h1>Overview Media</h1>*@

<table class="table table-bordered bg-danger">
    <thead>
        <tr>
            <th><a asp-controller="Movie" asp-action="Index" class="text-center btn-outline-info">MOVIES </a></th>
            <th><a asp-controller="Serie" asp-action="Index" class="btn-outline-info">SERIES </a></th>
            <th><a asp-controller="Music" asp-action="Index" class="btn-outline-info">MUSIC </a></th>
            <th><a asp-controller="Podcast" asp-action="Index" class="btn-outline-info">PODCASTS </a></th>
        </tr>
    </thead>
</table>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>@Html.DisplayNameFor(model => model.ListMediaViewModels[0].Title)</th>
            <th>@Html.DisplayNameFor(model => model.ListMediaViewModels[0].Country)</th>
            <th>@Html.DisplayNameFor(model => model.ListMediaViewModels[0].Genre)</th>
            <th>Media</th>
        </tr>
        <tr>
            <th></th>
            <th>
                <form asp-controller="Media" asp-action="Index" method="get">
                    <p>
                        <input type="text" name="SearchTitle" />
                        <input type="Submit" value="Search" />
                    </p>
                </form>
            </th>
            <th>
            </th>
            <th>
                <form asp-controller="Media" asp-action="Index" method="get">
                    <p>
                        <select asp-for="MediaGenre" asp-items="Model.Genres">
                            @*<select asp-for="MediaGenre" asp-items="Model.Genres as IEnumerable<SelectListItem>">*@
                            <option value="">All</option>
                        </select>
                        <input type="Submit" value="Search" />
                    </p>
                </form>
            </th>
            <th>
                @*<form asp-controller="Media" asp-action="Index" method="get">
                        <p>
                            <input type="text" name="SearchType"  maxlength="8"/>
                            <input type="Submit" value="Search" />
                        </p>
                    </form>*@
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ListMediaViewModels)
        {
            <tr>
                <td><img src="@item.PosterUrl" class="img-thumbnail" style="height:100px;width:70px" /></td>
                <td>@item.Title</td>
                <td>@item.Country</td>
                <td>@item.Genre</td>
                <td>@item.Descriminator</td>
            </tr>
        }
    </tbody>
</table>


@*<td>@item.ReleaseDate.ToString("yyyy-MM-dd")</td>*@
@*<td>@Html.DisplayFor(viewitem => item.Title)</td>
    <td>@Html.DisplayFor(viewitem => item.ReleaseDate)</td>
    <td>@Html.DisplayFor(viewitem => item.typeof(SelectListItem) )</td>*@